objects:
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /openshift/jenkins/pv/ 
    server: 10.92.112.76
  persistentVolumeReclaimPolicy: Recycle
