objects:
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /openshift/pv/nexus
    server: 10.92.112.76
  persistentVolumeReclaimPolicy: Recycle
