---
- name: jenkinsPipelineConfig
  lineinfile:
    path: "/etc/origin/master/master-config.yaml"
    regexp: "^jenkinsPipelineConfig:"
    insertbefore: '^kind: MasterConfig$'
    line: 'jenkinsPipelineConfig:'

- name: jenkinsPipelineConfig2
  lineinfile:
    path: "/etc/origin/master/master-config.yaml"
    regexp: "^  autoProvisionEnabled:"
    insertafter: '^jenkinsPipelineConfig:$'
    line: '  autoProvisionEnabled: false'
